### PR TITLE
Fix - Duplicated info text when pressing tooltip

### PR DESCRIPTION
**Pull request by alecook**
Updated tooltip for version fixes

### CODE REVIEW

**Comment by jasongaare** [comment]
Hello. Thanks for using `react-native-walkthrough-tooltip`. 

Have you tried using `showChildInTooltip={false}` to avoid displaying the duplicated child?
Also, the linked issue I'm not certain is the same you are describing. If there's an issue with android when the keyboard is open, I'd love to have a reproduction and try to resolve it for you! Thanks

**Comment by jasongaare** [comment]
Further, if the fix from the issue did help, `v1.1.0` should contain the fix

**Comment by alecook** [comment]
Hey @jasongaare! I did try using `showChildInTooltip={false}` and it did not seem to help this case. I can come up with some reproduction steps and submit a bug.

The fix from the post did work for me! I'll try out that version and see how that goes. Thanks for the reply

**Comment by alecook** [comment]
@jasongaare Just an FYI looks like 1.1.0 fixed my issues. Thanks!

**Pull request merged**
